export const PERMISSIONS = {
  USERS_CREATE: 'users:create',
  USERS_READ: 'users:read',
  USERS_UPDATE: 'users:update',
  USERS_DELETE: 'users:delete',
  ROLES_CREATE: 'roles:create',
  ROLES_READ: 'roles:read',
  ROLES_UPDATE: 'roles:update',
  ROLES_DELETE: 'roles:delete',
  AUDIT_LOGS_READ: 'audit-logs:read',
  ORGANIZATIONS_READ: 'organizations:read',
  ORGANIZATIONS_UPDATE: 'organizations:update',
  SITES_CREATE: 'sites:create',
  SITES_READ: 'sites:read',
  SITES_UPDATE: 'sites:update',
  SITES_DELETE: 'sites:delete',
  BUILDINGS_CREATE: 'buildings:create',
  BUILDINGS_READ: 'buildings:read',
  BUILDINGS_UPDATE: 'buildings:update',
  BUILDINGS_DELETE: 'buildings:delete',
  FLOORS_CREATE: 'floors:create',
  FLOORS_READ: 'floors:read',
  FLOORS_UPDATE: 'floors:update',
  FLOORS_DELETE: 'floors:delete',
  ZONES_CREATE: 'zones:create',
  ZONES_READ: 'zones:read',
  ZONES_UPDATE: 'zones:update',
  ZONES_DELETE: 'zones:delete',
  CAMERAS_CREATE: 'cameras:create',
  CAMERAS_READ: 'cameras:read',
  CAMERAS_UPDATE: 'cameras:update',
  CAMERAS_DELETE: 'cameras:delete',
  CAMERAS_TEST_CONNECTION: 'cameras:test-connection',
  CAMERAS_DISCOVER: 'cameras:discover',
  CAMERAS_STREAM: 'cameras:stream',
  CAMERA_GROUPS_CREATE: 'camera-groups:create',
  CAMERA_GROUPS_READ: 'camera-groups:read',
  CAMERA_GROUPS_UPDATE: 'camera-groups:update',
  CAMERA_GROUPS_DELETE: 'camera-groups:delete',
  RECORDINGS_CREATE: 'recordings:create',
  RECORDINGS_READ: 'recordings:read',
  RECORDINGS_DELETE: 'recordings:delete',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export interface PermissionDefinition {
  key: PermissionKey;
  description: string;
}

export const PERMISSION_DEFINITIONS: PermissionDefinition[] = [
  { key: PERMISSIONS.USERS_CREATE, description: 'Create users' },
  { key: PERMISSIONS.USERS_READ, description: 'View users' },
  { key: PERMISSIONS.USERS_UPDATE, description: 'Update users and their role assignments' },
  { key: PERMISSIONS.USERS_DELETE, description: 'Deactivate users' },
  { key: PERMISSIONS.ROLES_CREATE, description: 'Create roles' },
  { key: PERMISSIONS.ROLES_READ, description: 'View roles and their permissions' },
  { key: PERMISSIONS.ROLES_UPDATE, description: 'Update roles and their permission assignments' },
  { key: PERMISSIONS.ROLES_DELETE, description: 'Delete non-system roles' },
  { key: PERMISSIONS.AUDIT_LOGS_READ, description: 'View audit logs' },
  { key: PERMISSIONS.ORGANIZATIONS_READ, description: "View the caller's organization" },
  { key: PERMISSIONS.ORGANIZATIONS_UPDATE, description: "Update the caller's organization" },
  { key: PERMISSIONS.SITES_CREATE, description: 'Create sites' },
  { key: PERMISSIONS.SITES_READ, description: 'View sites' },
  { key: PERMISSIONS.SITES_UPDATE, description: 'Update sites' },
  { key: PERMISSIONS.SITES_DELETE, description: 'Delete sites' },
  { key: PERMISSIONS.BUILDINGS_CREATE, description: 'Create buildings' },
  { key: PERMISSIONS.BUILDINGS_READ, description: 'View buildings' },
  { key: PERMISSIONS.BUILDINGS_UPDATE, description: 'Update buildings' },
  { key: PERMISSIONS.BUILDINGS_DELETE, description: 'Delete buildings' },
  { key: PERMISSIONS.FLOORS_CREATE, description: 'Create floors' },
  { key: PERMISSIONS.FLOORS_READ, description: 'View floors' },
  { key: PERMISSIONS.FLOORS_UPDATE, description: 'Update floors' },
  { key: PERMISSIONS.FLOORS_DELETE, description: 'Delete floors' },
  { key: PERMISSIONS.ZONES_CREATE, description: 'Create zones' },
  { key: PERMISSIONS.ZONES_READ, description: 'View zones' },
  { key: PERMISSIONS.ZONES_UPDATE, description: 'Update zones' },
  { key: PERMISSIONS.ZONES_DELETE, description: 'Delete zones' },
  { key: PERMISSIONS.CAMERAS_CREATE, description: 'Create cameras' },
  { key: PERMISSIONS.CAMERAS_READ, description: 'View cameras' },
  { key: PERMISSIONS.CAMERAS_UPDATE, description: 'Update cameras' },
  { key: PERMISSIONS.CAMERAS_DELETE, description: 'Delete cameras' },
  { key: PERMISSIONS.CAMERAS_TEST_CONNECTION, description: 'Run a camera connectivity check' },
  { key: PERMISSIONS.CAMERAS_DISCOVER, description: 'Run an ONVIF network discovery sweep' },
  {
    key: PERMISSIONS.CAMERAS_STREAM,
    description: 'Start/stop/view a live RTSP-to-browser preview of a camera',
  },
  { key: PERMISSIONS.CAMERA_GROUPS_CREATE, description: 'Create camera groups' },
  { key: PERMISSIONS.CAMERA_GROUPS_READ, description: 'View camera groups' },
  {
    key: PERMISSIONS.CAMERA_GROUPS_UPDATE,
    description: 'Update camera groups and their membership',
  },
  { key: PERMISSIONS.CAMERA_GROUPS_DELETE, description: 'Delete camera groups' },
  { key: PERMISSIONS.RECORDINGS_CREATE, description: 'Upload a video recording' },
  { key: PERMISSIONS.RECORDINGS_READ, description: 'View/play back uploaded recordings' },
  { key: PERMISSIONS.RECORDINGS_DELETE, description: 'Delete an uploaded recording' },
];
